{{- $clamav := .Values.global.control.clamav }}
{{- if $clamav.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.appPort }}
      targetPort: clamd
      protocol: TCP
      name: clamd
  selector:
    {{- include "clamav.labels" . | nindent 4 }}
{{- end }}
