{{- if .Values.global.control.redis }}
{{- if .Values.global.control.redis.internal }}
{{- if eq .Values.global.storage "efs" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: control-{{ .Values.appName }}-{{ .Values.global.storage}}-{{ .Release.Name }}
  labels:
    {{- include "control.redis.labels" . | nindent 4 }}
    application: control-{{ .Values.appName }}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  claimRef:
    name: {{ .Values.global.redis.persistantVolumeClaimName }}
    namespace: {{ .Release.Namespace }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.global.storageClassName }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.global.efs.efsFileSystemId }}
{{- end }}
{{- end }}
{{- end }}
