{{- define "claude-code-api.container_envs_db" -}}
{{- $claude_code_api_data := .Values.global.control.claude_code_api }}
{{- $db_secret_data := $claude_code_api_data.db.secret.data }}
{{- if $claude_code_api_data.db.secret.create }}
{{- $db_secret_name := ( include "claude-code-api.postgresSecretName" . ) }}
- name: DB_HOST
  valueFrom:
    secretKeyRef:
      name: {{ $db_secret_name }}
      key: dbhost
- name: DB_PORT
  valueFrom:
    secretKeyRef:
      name: {{ $db_secret_name }}
      key: dbport
- name: DB_USER
  valueFrom:
    secretKeyRef:
      name: {{ $db_secret_name }}
      key: dbuser
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ $db_secret_name }}
      key: dbpwd
{{- if $db_secret_data.dbname }}
- name: DB_NAME
  valueFrom:
    secretKeyRef:
      name: {{ $db_secret_name }}
      key: dbname
{{- else }}
- name: DB_NAME
  value: {{ $claude_code_api_data.dbname | default "claude_code" }}
{{- end }}
{{- if $db_secret_data.sslmode }}
- name: DB_SSLMODE
  valueFrom:
    secretKeyRef:
      name: {{ $db_secret_name }}
      key: sslmode
{{- else }}
- name: DB_SSLMODE
  value: disable
{{- end }}
{{- else }}
- name: DB_HOST
  value: {{ $db_secret_data.dbhost | quote }}
- name: DB_PORT
  value: {{ $db_secret_data.dbport | quote }}
- name: DB_USER
  value: {{ $db_secret_data.dbuser | quote }}
- name: DB_PASSWORD
  value: {{ $db_secret_data.dbpwd | quote }}
{{- if $db_secret_data.dbname }}
- name: DB_NAME
  value: {{ $db_secret_data.dbname | quote }}
{{- else }}
- name: DB_NAME
  value: {{ $claude_code_api_data.dbname | default "claude_code" }}
{{- end }}
{{- if $db_secret_data.sslmode }}
- name: DB_SSLMODE
  value: {{ $db_secret_data.sslmode | quote }}
{{- else }}
- name: DB_SSLMODE
  value: disable
{{- end }}
{{- end }}
{{- end }}
