{{- $claude_code_api_data := .Values.global.control.claude_code_api }}
{{- if and (hasKey .Values.global.control "claude_code_api") (hasKey .Values.global.control.claude_code_api "enabled") $claude_code_api_data.enabled }}
{{- if $claude_code_api_data.db.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "claude-code-api.postgresSecretName" . }}
  labels:
    {{- include "claude-code-api.labels" . | nindent 4 }}
type: Opaque
data:
  dbhost: {{ $claude_code_api_data.db.secret.data.dbhost | b64enc }}
  dbport: {{ $claude_code_api_data.db.secret.data.dbport | b64enc }}
  dbuser: {{ $claude_code_api_data.db.secret.data.dbuser | b64enc }}
  dbpwd: {{ $claude_code_api_data.db.secret.data.dbpwd | b64enc }}
  {{- if $claude_code_api_data.db.secret.data.dbname }}
  dbname: {{ $claude_code_api_data.db.secret.data.dbname | b64enc }}
  {{- end }}
  {{- if $claude_code_api_data.db.secret.data.sslmode }}
  sslmode: {{ $claude_code_api_data.db.secret.data.sslmode | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
