{{- if and (hasKey .Values.global.control "claude_code_api") (hasKey .Values.global.control.claude_code_api "enabled") .Values.global.control.claude_code_api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  labels:
    {{- include "claude-code-api.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.global.control.claude_code_api.annotations | nindent 4 }}
spec:
  selector:
    {{- include "claude-code-api.labels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
{{- end }}
