apiVersion: v2
name: control
description: A Helm chart for Control
icon: https://sim.simulator.company/static/logo.svg
type: application
version: 0.3.66
appVersion: 5.142.0

dependencies:
  - name: server
    version: 0.3.62
    repository: file://charts/server
  - name: frontend
    version: 0.3.61
    repository: file://charts/frontend
  - name: realtime
    version: 0.3.17
    repository: file://charts/realtime
  - name: control-tasks
    version: 0.1.31
    repository: file://charts/control-tasks
  - name: widget
    version: 0.3.52
    repository: file://charts/widget
  - name: ctrl-sim-api
    version: 0.1.1
    repository: file://charts/ctrl-sim-api
    condition: global.control.ctrl_sim_api.enabled
  - name: sim-vector
    version: 0.1.0
    repository: file://charts/sim-vector
    condition: global.control.sim_vector.enabled
  - name: sim-tei
    version: 0.1.0
    repository: file://charts/sim-tei
    condition: global.control.simTei.enabled
  - name: sim-tei-sparse
    version: 0.1.0
    repository: file://charts/sim-tei-sparse
    condition: global.control.simTeiSparse.enabled
  - name: sim-vector-diskann
    version: 0.1.0
    repository: file://charts/sim-vector-diskann
    condition: global.control.sim_vector_diskann.enabled
  - name: claude-code-api
    version: 0.1.3
    repository: file://charts/claude-code-api
    condition: global.control.claude_code_api.enabled
