apiVersion: v1
data:
  control_realtime.yml: |
    port: {{ .Values.global.control.realtimePort }}
    redis:
      host: {{ .Values.global.redis.secret.data.host }}
      port: {{ .Values.global.redis.secret.data.port }}
      {{ if .Values.global.redis.secret.data.password }}password: {{ .Values.global.redis.secret.data.password }}{{ end }}
      pool:
        max: 50
        idle: 30000
    redisPubSub:
      host: {{ .Values.global.redis.secret.data.host }}
      port: {{ .Values.global.redis.secret.data.port }}
      {{ if .Values.global.redis.secret.data.password }}password: {{ .Values.global.redis.secret.data.password }}{{ end }}
      pool:
        max: 50
        idle: 30000
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  labels:
{{- include "realtime.labels" . | nindent 4 }}