{{- $global_data := .Values.global }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "control.realtime.configmap.name" . }}
  labels:
{{- include "realtime.labels" . | nindent 4 }}
data:
  control_realtime.yml: |
    port: ${CONTROL_REALTIME_PORT}
    session:
      ttl: ${CONTROL_REALTIME_SESSION_TTL}
      cookieName: ${CONTROL_REALTIME_SESSION_COOKIENAME}
    {{- if and (hasKey .Values.global.redis "cluster") (.Values.global.redis.cluster.enable) }}
    redisCluster:
      nodes:
      {{- range .Values.global.redis.cluster.nodes }}
        - host: {{ .host }}
          port: {{ .port }}
          password: ${REDIS_PASSWORD}
          db: ${REDIS_DATABASE}
      {{- end }}
      {{- if .Values.global.redis.secret.data.password }}
      password: ${REDIS_PASSWORD}
      {{- end }}
      {{- include "control.realtime.redis.pool" . | nindent 6 }}
    {{- else }}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      {{- if .Values.global.redis.secret.data.password }}
      password: ${REDIS_PASSWORD}
      {{- end }}
      {{- if .Values.global.control.redisDb }}
      db: ${REDIS_DATABASE}
      {{- end }}
      {{- include "control.realtime.redis.pool" . | nindent 6 }}
    {{- end }}
    {{- if and (hasKey .Values.global.redis "cluster") (.Values.global.redis.cluster.enable) }}
    redisPubSubCluster:
      nodes:
      {{- range .Values.global.redis.cluster.nodes }}
        - host: {{ .host }}
          port: {{ .port }}
          password: ${REDIS_PASSWORD}
          db: ${REDIS_DATABASE}
      {{- end }}
      {{- if .Values.global.redis.secret.data.password }}
      password: ${REDIS_PASSWORD}
      {{- end }}
      {{- include "control.realtime.redisPubSub.pool" . | nindent 6 }}
    {{- else }}
    redisPubSub:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      {{- if .Values.global.redis.secret.data.password }}
      password: ${REDIS_PASSWORD}
      {{- end }}
      {{- if .Values.global.control.redisDb }}
      db: ${REDIS_DATABASE}
      {{- end }}
      {{- include "control.realtime.redisPubSub.pool" . | nindent 6 }}
    {{- end }}
    {{- if .Values.global.control.scylladb }}
    scylladb:
      contactPoints:
    {{- if .Values.global.control.scylladb.internal }}
        - scylla-service
    {{- else }}
      {{- range .Values.global.control.scylladb.contactPoints }}
        - {{ . }}
      {{- end }}
    {{- end }}
      keyspace: {{ .Values.global.control.scylladb.keyspace }}
      localDataCenter: {{ .Values.global.control.scylladb.localDataCenter }}
    {{- end }}
    {{- if and (hasKey .Values.global.control.realtime "config") (hasKey .Values.global.control.realtime.config "firebase") }}
    firebase: |
      {{ .Values.global.control.realtime.config.firebase }}
    {{- end }}
    {{- if and (hasKey .Values.global.control.realtime "config") (hasKey .Values.global.control.realtime.config "ios_push_kit") }}
    ios_push_kit:
      certs:
        default:
          store_type: {{ .Values.global.control.realtime.config.ios_push_kit.certs.default.store_type }}
          aws_secret:
            region: {{ .Values.global.control.realtime.config.ios_push_kit.certs.default.aws_secret.region }}
            name: {{ .Values.global.control.realtime.config.ios_push_kit.certs.default.aws_secret.name }}
    {{- end }}
    metrics:
      port: {{ include "control.realtime.metrics_port" . }}
