{{- $global_data := .Values.global }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "control.realtime.configmap.name" . }}
  labels:
{{- include "realtime.labels" . | nindent 4 }}
data:
  control_realtime.yml: |
    port: ${CONTROL_REALTIME_PORT}
    session:
      ttl: ${CONTROL_REALTIME_SESSION_TTL}
      cookieName: ${CONTROL_REALTIME_SESSION_COOKIENAME}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      {{- if .Values.global.redis.secret.data.password }}
      password: ${REDIS_PASSWORD}
      {{- end }}
      {{- if .Values.global.control.redisDb }}
      db: ${REDIS_DATABASE}
      {{- end }}
      pool:
        max: 50
        idle: 30000
    redisPubSub:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      {{- if .Values.global.redis.secret.data.password }}
      password: ${REDIS_PASSWORD}
      {{- end }}
      {{- if .Values.global.control.redisDb }}
      db: ${REDIS_DATABASE}
      {{- end }}
      pool:
        max: 50
        idle: 30000
    metrics:
      port: {{ include "control.realtime.metrics_port" . }}
