{{- $global_data := .Values.global }}
{{- $control_data := $global_data.control }}
{{- $realtime_data := $control_data.realtime }}
{{- if eq .Values.hpa_mem true }}
{{- if semverCompare "<=1.22-0" .Capabilities.KubeVersion.Version -}}
{{- if $realtime_data.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appName }}-memory-autoscale
  labels:
{{- include "realtime.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}-deployment
  minReplicas: {{ $realtime_data.autoscaling.minReplicas }}
  maxReplicas: {{ $realtime_data.autoscaling.maxReplicas }}
  metrics:
    {{- if $realtime_data.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $realtime_data.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 180
      policies:
        - type: Pods
          value: 6
          periodSeconds: 120
        - type: Percent
          value: 10
          periodSeconds: 120
      selectPolicy: Max
{{- end }}
{{- end }}
{{- end }}