{{- $global_data := .Values.global }}
{{- $control_data := $global_data.control }}
{{- $realtime_data := $control_data.realtime }}
{{- if $realtime_data.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appName }}-cpu-autoscale
  labels:
{{- include "realtime.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}-deployment
  minReplicas: {{ $realtime_data.autoscaling.minReplicas }}
  maxReplicas: {{ $realtime_data.autoscaling.maxReplicas }}
  {{- if $realtime_data.autoscaling.targetCPUUtilizationPercentage }}
  targetCPUUtilizationPercentage: {{ $realtime_data.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
{{- end }}
