{{- if ( .Values.global.elasticsearch.internal )}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    app: {{ .Values.global.control.product }}
    tier: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.control.product }}
        tier: {{ .Values.appName }}
    spec:
      {{- if not (eq .Values.global.control.repotype "public") }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets.name }}
      {{- end }}
      initContainers:
        - name: increase-vm-max-map
          image: docker-hub.middleware.biz/hub.docker.com/library/busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: docker-hub.middleware.biz/hub.docker.com/library/busybox
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
      containers:
        - name: {{ .Values.appName }}
          imagePullPolicy: {{ .Values.global.control.imagePullPolicy | default "IfNotPresent" }}
          image: "{{ .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: ES_JAVA_OPTS
              value: "-Xmx1g -Xms1g -Dlog4j2.formatMsgNoLookups=true"
          ports:
            - name: es
              protocol: TCP
              containerPort: {{ .Values.appPort }}
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: {{ .Values.appPort }}
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              path: /_cluster/health?local=true
              port: {{ .Values.appPort }}
            initialDelaySeconds: 90
{{- end }}
