appName: control-tasks

image:
  repository: ctrl-control-tasks

appReadinessHttpPort: 9000
appReadinessHttpPath: "/ready"
appLivenessHttpPath: "/ready"
configPath: "/ebsmnt/conf"
configName: "config.yml"