{{- if and (hasKey .Values "global") (hasKey .Values.global.control "simTei") (.Values.global.control.simTei.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  labels:
    {{- include "sim-tei.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sim-tei.selectorLabels" . | nindent 4 }}
{{- end }}
