apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  labels:
{{- include "server.labels" . | nindent 4 }}
data:
  control.yml: |
    port: {{ .Values.global.control.serverPort }} # Application port
    apiVersion: "{{ .Values.global.control.apiVersion }}" # API version
    apiSecret: {{ .Values.global.control.apiSecret }} # Secret for submitting requests between Control applications.
    browserExtensionsSecret: {{ .Values.global.control.browserExtensionsSecret }}
    googleApiKey: {{ .Values.global.control.googleApiKey }}
    superAdminApiKey: {{ .Values.global.control.superAdminApiKey }} # Superadmin API key
    locales: {{- range .Values.global.control.locales }} # Supported localizations
      - {{.}}{{- end }}
    timeZone: {{ .Values.global.control.timeZone }} # Time zone from which time is calculated in notification letters.

    enableAPI: ${ENABLE_API} # Enable api mode
    enableCrons: false # Enable cron mode
    logLevel: {{ .Values.global.control.loglevel | default "custom" }}
    http2: false
    session:
      ttl: {{ .Values.global.control.session.ttl }}
      cookieName: {{ .Values.global.control.session.cookieName }}

    connectors:
      apiLogin: {{ .Values.global.control.connectors.apiLogin }}
      apiSecret: {{ .Values.global.control.connectors.apiSecret }}
      convId: {{ .Values.global.control.connectors.convId }}
      syncApiUrl: {{ .Values.global.control.connectors.syncApiUrl }}

    auth: # Auth settings via Single Account
      disablePublicApiCheck: {{ .Values.global.control.auth.disablePublicApiCheck }}
      name: {{ .Values.global.control.auth.name }}
      saSecretKey: {{ .Values.global.control.auth.key }}
      url: https://{{ .Values.global.control.auth.domain }}

    trackUrl: https://{{- include "control.Domain" . }} # Control Admin domain
    apiCorezoid: https://{{ .Values.global.control.apiCorezoidDomain }} # Corezoid Api domain
    adminCorezoid: https://{{ .Values.global.control.adminCorezoidDomain }} # Corezoid Admin domain
    corezoidSyncApiUrl: {{ .Values.global.control.corezoidSyncApiUrl }}

    db: # PostgreSQL settings
      mainDB: # PostgreSQL Main DB settings
        name: {{ .Values.global.db.secret.data.dbname | default "control" }}
        userName: {{ .Values.global.db.secret.data.dbuser }}
        password: {{ .Values.global.db.secret.data.dbpwd }}
        settings:
          {{- if .Values.global.db.bouncer }}
          host: pgbouncer-service
          port: {{ .Values.global.db.bouncer_port }}
          {{- else }}
          host: {{ .Values.global.db.secret.data.dbhost }}
          port: {{ .Values.global.db.secret.data.dbport }}
          {{- end }}
          dialect: postgres
          logging: false
          {{- include "control.server.db.pool" . | nindent 10 }}

    redis: # Redis cache settings
      host: {{ .Values.global.redis.secret.data.host }}
      port: {{ .Values.global.redis.secret.data.port }}
      {{- if .Values.global.redis.secret.data.password }}
      password: {{ .Values.global.redis.secret.data.password }}
      {{- end }}
      {{- if .Values.global.control.redisDb }}
      db: {{ .Values.global.control.redisDb }}
      {{- end }}
      pool:
        min: 2
        max: 50
        idle: 30000

    redisPubSub: # Redis PubSub settings for Real-Time
      host: {{ .Values.global.redis.secret.data.host_PubSub }}
      port: {{ .Values.global.redis.secret.data.port_PubSub}}
      {{- if .Values.global.redis.secret.data.password }}
      password: {{ .Values.global.redis.secret.data.password }}
      {{- end }}
      {{- if .Values.global.control.redisDb }}
      db: {{ .Values.global.control.redisDb }}
      {{- end }}
      pool:
        min: 2
        max: 50
        idle: 30000

    corezoid: # Corezoid processes settings
      apiSecret: "{{ .Values.global.control.corezoid.apiSecret }}"
      companyId: {{ .Values.global.control.corezoid.companyId }} # Corezoid company ID with Control processes
      processes:
        sendEmail: # Corezoid process for send email
          directUrl: {{ .Values.global.control.corezoid.processes.sendEmail.directUrl }}
          convId: {{ .Values.global.control.corezoid.processes.sendEmail.convId }}
        accRegistrations: # Corezoid process for Control registrations
          directUrl: {{ .Values.global.control.corezoid.processes.accRegistrations.directUrl }}
          convId: {{ .Values.global.control.corezoid.processes.accRegistrations.convId }}

    requestLimits:
      ip: {{ .Values.global.control.requestLimits.ip }}

    filesStorage: # Shared folder for uploaded files
      eventFiles: {{ .Values.global.control.filesStorage.eventFiles }}

    webConfig: # Client settings while startup
      avatarPath: https://{{ .Values.global.control.auth.domain }}/avatars/52x52/{userId}.jpg # Avatar regexp
      systemUserAvatar: https://{{- include "control.Domain" . }}/static/systemUserAvatar.svg # System suer avatar
      adminCorezoid: https://{{ .Values.global.control.adminCorezoidDomain }} # Corezoid Admin domain
      widgetUrl: https://{{- include "control.WidgetDomain" . }} # Control widget host
      supportEmail: {{ .Values.global.control.webConfig.supportEmail }} # Email for support
      realtimeApi: wss://{{- include "control.Domain" . }} # Control-realtime host
      apiDoc: https://{{- include "control.Domain" . }}/api.html # API doc host
      maxFileSize: {{ .Values.global.control.webConfig.maxFileSize }} # Max filesize
      {{- if .Values.global.control.webConfig.controlWidgetId }}
      controlWidgetId: {{ .Values.global.control.webConfig.controlWidgetId }}
      {{- end }}
      {{- if .Values.global.control.webConfig.googleAnalytics }}
      googleAnalytics: {{ .Values.global.control.webConfig.googleAnalytics }}
      {{- end }}
      {{- if .Values.global.control.webConfig.fileMimeTypes }}
      fileMimeTypes: {{ .Values.global.control.webConfig.fileMimeTypes }}
      {{- end }}

    channels:
      gmail:
        clientId: {{ .Values.global.control.channels.gmail.clientId }}
        clientSecret: {{ .Values.global.control.channels.gmail.clientSecret }}
        ignoredDomains: {{- range .Values.global.control.channels.gmail.ignoredDomains }}
          - {{.}}{{- end }}
