{{- $global_data := .Values.global }}
{{- $control_data := $global_data.control }}
{{- $server_data := $global_data.control.server }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
{{- include "server.labels" . | nindent 4 }}
spec:
{{- if $server_data.autoscaling.enabled }}
  replicas: {{ $server_data.autoscaling.minReplicas }}
{{- end }}
  selector:
    matchLabels:
{{- include "server.labels" . | nindent 6 }}
{{- with $global_data.deploymentStrategy }}
  strategy:
{{ toYaml . | trim | indent 4 }}
{{- end }}
{{- if eq $global_data.deploymentStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
{{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- include "control.server.annotations" . | nindent 4 }}
      labels:
{{- include "server.labels" . | nindent 8 }}
    spec:
      {{- if $server_data.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ $server_data.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.global.imagePullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
      {{- end }}
      {{- if .Values.global.control.frontend.serviceAccount }}
      {{- if .Values.global.control.frontend.serviceAccount.create }}
      serviceAccountName: control-{{ .Values.appName }}-serviceaccount
      {{- end }}
      {{- end }}
      securityContext:
        {{- toYaml $control_data.podSecurityContext | nindent 8 }}
      initContainers:
        {{ include "InitWait.postgres" . | nindent 8 }}

        {{ include "InitWait.postgres-extension-postgis" . | nindent 8 }}

        {{ include "InitWait.postgres-extension-btree-gin" . | nindent 8 }}

        {{ include "InitWait.postgres-extension-pg-trgm" . | nindent 8 }}

        {{ include "InitWait.bouncer" . | nindent 8 }}

        {{ include "InitWait.redis" . | nindent 8 }}

        {{ include "InitWait.scylla" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml $control_data.securityContext | nindent 12 }}
          image: {{ include "server.imageUrl" . | quote }}
          imagePullPolicy: {{ $server_data.pullPolicy }}
          env:
            - name: ENABLE_API
              value: "true"
            - name: ENABLE_CRONS
              value: "false"
            - name: K8S
              value: "true"
            {{- if $server_data.selfsigned }}
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            {{- end }}
            {{- if $server_data.allow_autotests }}
            - name: ALLOW_AUTOTESTS
              value: {{ $server_data.allow_autotests | quote }}
            {{- end }}
            - name: CONTROL_DOMAIN
              value: {{ include "control.Domain" . }}
            {{- include "control.container_envs_redis" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ include "server.port" . }}
              protocol: TCP
          {{ include "server.liveness" . | nindent 10 }}
          {{ include "server.readiness" . | nindent 10 }}
          resources:
            {{- toYaml $server_data.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.appName }}-config-volume
              mountPath: /ebsmnt/conf/control.yml
              subPath: control.yml
            {{- if .Values.global.control.filesStorage.type }}
            {{- if and (ne .Values.global.control.filesStorage.type "s3") (ne .Values.global.control.filesStorage.type "cdn") }}
            - name: {{ .Values.appName }}-attachments
              mountPath: {{ $control_data.filesStorage.eventFiles }}
            {{- end }}
            {{- end }}
            {{- if or (eq .Values.global.efs.enabled true) (eq .Values.global.storage "manual") (eq .Values.global.storage "nfs") }}
            - name: {{ .Values.appName }}-attachments
              mountPath: {{ $control_data.filesStorage.eventFiles }}
            {{- end }}
      volumes:
        {{- if or (eq .Values.global.storage "manual") (eq .Values.global.storage "nfs") }}
        - name: {{ .Values.appName }}-attachments
          persistentVolumeClaim:
            claimName: {{ $control_data.server.persistantVolumeClaimName }}
        {{- end }}
        {{- if eq .Values.global.efs.enabled true}}
        - name: {{ .Values.appName }}-attachments
          persistentVolumeClaim:
          nfs:
            server: {{ .Values.global.efs.efsFileSystemId }}.efs.{{ .Values.global.efs.awsRegion }}.amazonaws.com
            path: /
        {{- end }}
        - name: {{ .Values.appName }}-config-volume
          configMap:
            name: {{ .Values.appName }}-configmap
        {{- if .Values.global.control.filesStorage.type }}
        {{- if and (ne .Values.global.control.filesStorage.type "s3") (ne .Values.global.control.filesStorage.type "cdn") }}
        {{- if $server_data.persistantVolumeClaimCreate }}
        - name: {{ .Values.appName }}-attachments
          persistentVolumeClaim:
            claimName: {{ $server_data.persistantVolumeClaimName }}
            readOnly: false
        {{- end }}
        {{- end }}
        {{- end }}
      {{- with $control_data.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $control_data.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $control_data.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
