{{- if eq .Values.global.efs.enabled true}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: control-efs-shared-pvc
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.global.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.global.efs.storageSize | default "5Gi" }}
{{- end }}
