{{- if .Values.global.control.server.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appName }}-cpu-autoscale
  labels:
{{- include "server.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}-deployment
  minReplicas: {{ .Values.global.control.server.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.global.control.server.autoscaling.maxReplicas }}
  {{- if .Values.global.control.server.autoscaling.targetCPUUtilizationPercentage }}
  targetCPUUtilizationPercentage: {{ .Values.global.control.server.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
{{- end }}

