{{- if .Values.global.control.server.persistantVolumeClaimCreate }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.control.server.persistantVolumeClaimName }}
  labels:
{{- include "server.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.global.storageClassName }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{- end }}