{{- if .Values.global.control.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{- include "server.labels" . | nindent 4 }}
  {{- with .Values.global.control.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
