{{- if .Values.global.control.server.serviceAccount -}}
{{- if .Values.global.control.server.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-{{ .Values.appName }}-serviceaccount
  labels:
    {{- include "server.labels" . | nindent 4 }}
  {{- with .Values.global.control.server.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
