{{- if and (hasKey .Values.global.control "ctrl_sim_api") (hasKey .Values.global.control.ctrl_sim_api "enabled") .Values.global.control.ctrl_sim_api.enabled .Values.global.control.ctrl_sim_api.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "control.configSecretName" . }}-{{ .Values.appName }}-reader-role
  labels:
{{- include "ctrl-sim-api.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [
      {{ include "control.configSecretName" . | quote }},
      {{ include "control.postgresSecretName" . | quote }},
      {{ include "control.redisSecretName" . | quote }}
    ]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: [{{ .Values.appName }}-configmap]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "control.configSecretName" . }}-{{ .Values.appName }}-reader-binding
  labels:
{{- include "ctrl-sim-api.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: control-{{ .Values.appName }}-serviceaccount
roleRef:
  kind: Role
  name: {{ include "control.configSecretName" . }}-{{ .Values.appName }}-reader-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-{{ .Values.appName }}-serviceaccount
  labels:
{{- include "ctrl-sim-api.labels" . | nindent 4 }}
  {{- with .Values.global.control.ctrl_sim_api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
