{
 "title": "Control Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [
  "nodejs",
  "golang",
  "Control"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(SubmittedTasks,namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nodejs_version_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Control-Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Requests Count per HTTP code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(25, sum by (status_code) (increase(http_request_duration_seconds_count{namespace=\"$namespace\"}[1m])>0))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Requests Count per API",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(25, sum by (method, route) (increase(http_request_duration_seconds_count{namespace=\"$namespace\"}[1m])>0))",
     "legendFormat": "{{method}} - {{route}}"
    }
   ]
  },
  {
   "title": "API Keys Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "topk(25, sum by (user_id, nick) (increase(http_api_key_request_duration_seconds_count{namespace=\"$namespace\"}[1m])>0))",
     "legendFormat": "{{user_id}} - {{nick}}"
    }
   ]
  },
  {
   "title": "Users Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "topk(25, sum by (user_id, nick) (increase(http_user_request_duration_seconds_count{namespace=\"$namespace\"}[1m])>0))",
     "legendFormat": "{{user_id}} - {{nick}}"
    }
   ]
  },
  {
   "title": "Median Response Time Overall",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\"}[1m])) by (le))",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Response Time per API",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_sum{namespace=\"$namespace\"}[1m])>0) by (method, route)/sum(increase(http_request_duration_seconds_count{namespace=\"$namespace\"}[1m])>0) by (method, route)",
     "legendFormat": "{{method}} - {{route}}"
    }
   ]
  },
  {
   "title": "API Keys Response Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(http_api_key_request_duration_seconds_sum{namespace=\"$namespace\"}[1m])>0) by (user_id, nick)/sum(increase(http_api_key_request_duration_seconds_count{namespace=\"$namespace\"}[1m])>0) by (user_id, nick)",
     "legendFormat": "{{user_id}} - {{nick}}"
    }
   ]
  },
  {
   "title": "Users Response Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(http_user_request_duration_seconds_sum{namespace=\"$namespace\"}[1m])>0) by (user_id, nick)/sum(increase(http_user_request_duration_seconds_count{namespace=\"$namespace\"}[1m])>0) by (user_id, nick)",
     "legendFormat": "{{user_id}} - {{nick}}"
    }
   ]
  },
  {
   "title": "Corezoid process Request Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "topk(25, sum by (processId) (increase(http_proc_request_summary_seconds_count{namespace=\"$namespace\"}[1m])>0))",
     "legendFormat": "{{processId}}"
    }
   ]
  },
  {
   "title": "Corezoid process Request Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(http_proc_request_duration_seconds_sum{namespace=\"$namespace\"}[1m])>0) by (processId)/sum(increase(http_proc_request_duration_seconds_count{namespace=\"$namespace\"}[1m])>0) by (processId)",
     "legendFormat": "{{processId}}"
    }
   ]
  },
  {
   "title": "Webhooks Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "topk(25, sum by (status_code) (increase(webhooks_duration_seconds_count{namespace=\"$namespace\"}[1m])>0))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Webhooks duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(webhooks_duration_seconds_sum{namespace=\"$namespace\"}[1m])>0) by ()/sum(increase(webhooks_duration_seconds_count{namespace=\"$namespace\"}[1m])>0) by ()",
     "legendFormat": "{{status_code}} "
    }
   ]
  },
  {
   "title": "Sync API Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "topk(25, sum by (method, status_code) (increase(api_gw_sync_response_time_seconds_count{namespace=\"$namespace\"}[1m])>0))",
     "legendFormat": "{{method}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Sync API Response time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(api_gw_sync_response_time_seconds_sum{namespace=\"$namespace\"}[1m])>0) by (method, status_code)/sum(increase(api_gw_sync_response_time_seconds_sum{namespace=\"$namespace\"}[1m])>0) by (method, status_code)",
     "legendFormat": "{{method}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Control-Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tasks WaitingTasks",
     "type": "timeseries",
     "description": "returns the current number of tasks waiting in the pool's queue",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "WaitingTasks{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tasks RunningWorkers",
     "type": "timeseries",
     "description": "returns the current number of running workers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "targets": [
      {
       "expr": "RunningWorkers{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tasks SubmittedTasks",
     "type": "timeseries",
     "description": "returns the total number of tasks submitted since the pool was created",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "SubmittedTasks{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tasks CompletedTasks",
     "type": "timeseries",
     "description": "returns the total number of tasks that have completed their execution either successfully or with panic since the pool was created",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "targets": [
      {
       "expr": "CompletedTasks{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tasks CountCreatedWaitTasks",
     "type": "timeseries",
     "description": "returns the total number of waiting tasks",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "targets": [
      {
       "expr": "CountCreatedWaitTasks{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tasks FailedTasks",
     "type": "timeseries",
     "description": "returns the total number of tasks that were completed with panic since the pool was created",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
     "targets": [
      {
       "expr": "FailedTasks{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Control-Realtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "collapsed": true,
   "panels": [
    {
     "title": "Real-time Connections Now",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
     "targets": [
      {
       "expr": "Connections{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Real-time Users",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
     "targets": [
      {
       "expr": "Users{namespace=\"$namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Real-time WS connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
     "targets": [
      {
       "expr": "sum(increase(RealtimeWsConnections{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Real-time WS unauthorized",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
     "targets": [
      {
       "expr": "sum(increase(RealtimeWsConnectionsUnauthorized{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Real-time Redis messages",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 144 },
     "targets": [
      {
       "expr": "sum(increase(RealtimeRedisMessagesCount{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Real-time WS messages",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 144 },
     "targets": [
      {
       "expr": "sum(increase(RealtimeWsMessagesCount{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Real-time RunningWorkers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 153 },
     "targets": [
      {
       "expr": "sum(increase(RealtimeRunningWorkers{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}