{
 "title": "SIM API",
 "description": "golang application metrics",
 "tags": [
  "golang",
  "Control"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(SubmittedTasks,namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nodejs_version_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "JSONRPC metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JSON-RPC requests (count)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(simapi_rpc_total{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JSON-RPC response (time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(simapi_rpc_duration_sum[1m])) / sum(rate(simapi_rpc_duration_count[1m])) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JSON-RPC per method (count)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(simapi_rpc_total{namespace=\"$namespace\"}[1m])) by (method) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JSON-RPC per method (time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(simapi_rpc_duration_sum{namespace=\"$namespace\"}[1m])>0) by (method)/sum(increase(simapi_rpc_duration_count{namespace=\"$namespace\"}[1m])>0) by (method)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JSON-RPC errors (count)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(increase(simapi_rpc_errors_total{namespace=\"$namespace\"}[1m])) by (code) ",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "JSON-RPC errors per method (count)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(increase(simapi_rpc_errors_total{namespace=\"$namespace\"}[1m])) by (method, code) ",
     "legendFormat": "{{method}}:{{code}}"
    }
   ]
  },
  {
   "title": "Postgres metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Postgres requests (count)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 513 },
     "targets": [
      {
       "expr": "sum(increase(simapi_postgres_total{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Postgres response (time)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 513 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(simapi_postgres_duration_sum[1m])) / sum(rate(simapi_postgres_duration_count[1m])) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Postgres per func (count)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 609 },
     "targets": [
      {
       "expr": "sum(increase(simapi_postgres_total{namespace=\"$namespace\"}[1m])) by (method) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Postgres per func (time)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 620 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(increase(simapi_postgres_duration_sum{namespace=\"$namespace\"}[1m])>0) by (method)/sum(increase(simapi_postgres_duration_count{namespace=\"$namespace\"}[1m])>0) by (method)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scylla metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scylla requests (count)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 514 },
     "targets": [
      {
       "expr": "sum(increase(simapi_scylla_total{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Scylla response (time)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 514 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(simapi_scylla_duration_sum[1m])) / sum(rate(simapi_scylla_duration_count[1m])) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Scylla per func (count)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 552 },
     "targets": [
      {
       "expr": "sum(increase(simapi_scylla_total{namespace=\"$namespace\"}[1m])) by (method) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Scylla per func (time)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 563 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(increase(simapi_scylla_duration_sum{namespace=\"$namespace\"}[1m])>0) by (method)/sum(increase(simapi_scylla_duration_count{namespace=\"$namespace\"}[1m])>0) by (method)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis requests (count)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 515 },
     "targets": [
      {
       "expr": "sum(increase(simapi_redis_total{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Redis response (time)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 515 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(simapi_redis_duration_sum[1m])) / sum(rate(simapi_redis_duration_count[1m])) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Redis per func (count)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 524 },
     "targets": [
      {
       "expr": "sum(increase(simapi_redis_total{namespace=\"$namespace\"}[1m])) by (method) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Redis per func (time)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 535 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(increase(simapi_redis_duration_sum{namespace=\"$namespace\"}[1m])>0) by (method)/sum(increase(simapi_redis_duration_count{namespace=\"$namespace\"}[1m])>0) by (method)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "External API metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "API account requests (count)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1297 },
     "targets": [
      {
       "expr": "sum(increase(simapi_api_account_total{namespace=\"$namespace\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "API account response (time)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1297 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(simapi_api_account_duration_sum[1m])) / sum(rate(simapi_api_account_duration_count[1m])) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "API account per func (count)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1306 },
     "targets": [
      {
       "expr": "sum(increase(simapi_api_account_total{namespace=\"$namespace\"}[1m])) by (method) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "API account per func (time)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1317 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(increase(simapi_api_account_duration_sum{namespace=\"$namespace\"}[1m])>0) by (method)/sum(increase(simapi_api_account_duration_count{namespace=\"$namespace\"}[1m])>0) by (method)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Api account http code (count)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1326 },
     "targets": [
      {
       "expr": "sum(increase(simapi_api_account_total{namespace=\"$namespace\"}[1m])) by (code) ",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Api account http code per func (count)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1335 },
     "targets": [
      {
       "expr": "sum(increase(simapi_api_account_total{namespace=\"$namespace\"}[1m])) by (method, code) ",
       "legendFormat": "{{method}}: {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API KEY metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "ApiKey requests (count)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1345 },
     "targets": [
      {
       "expr": "sum(increase(simapi_apikey_total{namespace=\"$namespace\"}[1m])) by (user, nick) ",
       "legendFormat": "{{nick}} ({{user}})"
      }
     ]
    },
    {
     "title": "ApiKey requests (time)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1354 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(increase(simapi_apikey_duration_sum{namespace=\"$namespace\"}[1m])>0) by (user, nick)/sum(increase(simapi_apikey_duration_count{namespace=\"$namespace\"}[1m])>0) by (user, nick)",
       "legendFormat": "{{nick}} ({{user}})"
      }
     ]
    },
    {
     "title": "ApiKey requests per method (count)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1363 },
     "targets": [
      {
       "expr": "sum(increase(simapi_apikey_total{namespace=\"$namespace\"}[1m])) by (method, user, nick) ",
       "legendFormat": "{{nick}} ({{user}}) - {{method}}"
      }
     ]
    },
    {
     "title": "ApiKey requests per method (time)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1372 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(increase(simapi_apikey_duration_sum{namespace=\"$namespace\"}[1m])>0) by (method, user, nick)/sum(increase(simapi_apikey_duration_count{namespace=\"$namespace\"}[1m])>0) by (method, user, nick)",
       "legendFormat": "{{nick}} ({{user}}) - {{method}}"
      }
     ]
    },
    {
     "title": "ApiKey errors (count)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1381 },
     "targets": [
      {
       "expr": "sum(increase(simapi_apikey_errors_total{namespace=\"$namespace\"}[1m])) by (user, nick) ",
       "legendFormat": "{{nick}} ({{user}})"
      }
     ]
    },
    {
     "title": "ApiKey errors per method (count)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1390 },
     "targets": [
      {
       "expr": "sum(increase(simapi_apikey_errors_total{namespace=\"$namespace\"}[1m])) by (method, user, nick) ",
       "legendFormat": "{{nick}} ({{user}}) - {{method}}"
      }
     ]
    },
    {
     "title": "ApiKey errors per code (count)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1399 },
     "targets": [
      {
       "expr": "sum(increase(simapi_apikey_errors_total{namespace=\"$namespace\"}[1m])) by (code, user, nick) ",
       "legendFormat": "{{nick}} ({{user}}) - {{code}}"
      }
     ]
    },
    {
     "title": "ApiKey errors per method/code (count)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1408 },
     "targets": [
      {
       "expr": "sum(increase(simapi_apikey_errors_total{namespace=\"$namespace\"}[1m])) by (method, code, user, nick) ",
       "legendFormat": "{{nick}} ({{user}}) - {{method}}:{{code}}"
      }
     ]
    }
   ]
  }
 ]
}