{{- if .Values.global.control.ingress.enabled -}}
{{- if .Values.global.control.apiOld -}}
{{- if .Values.global.control.apiOld.enabled -}}
{{- $fullName := include "control.fullname" . -}}
{{- $serverPort := .Values.global.control.serverPort -}}
{{- $frontendPort := .Values.global.control.frontendPort -}}
{{- $realtimePort := ( include "control.realtime.app_port" . ) -}}
{{- $widgetPort := .Values.global.control.widgetPort -}}
{{- if and .Values.global.control.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.global.control.ingress.annotations "kubernetes.io/ingress.class" .Values.global.control.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-domain-old
  labels:
    {{- include "control.labels" . | nindent 4 }}
  annotations:
    {{- include "control.ingressAnnotations" . | nindent 4 }}
spec:
  {{- if and .Values.global.control.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.global.control.ingress.className }}
  {{- end }}
  {{- if .Values.global.control.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.global.control.apiOld.controlSubDomainOld }}.{{ .Values.global.control.apiOld.mainDomain }}
        {{- if .Values.global.control.apiOld.controlSubDomainOldOld -}}
        - {{ .Values.global.control.apiOld.controlSubDomainOldOld }}.{{ .Values.global.domain }}
        {{- end }}
      secretName: tls-control
  {{- end }}
  rules:
    - host: {{ .Values.global.control.apiOld.controlSubDomainOld }}.{{ .Values.global.control.apiOld.mainDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: {{ $frontendPort }}
{{- if .Values.global.control.apiOld.controlSubDomainOldOld }}
    - host: {{ .Values.global.control.apiOld.controlSubDomainOldOld }}.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: {{ $frontendPort }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
