{{- $global_data := .Values.global }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "control.tasks.configmap.name" . }}
  labels:
    {{- include "control-tasks.labels" . | nindent 4 }}
data:
  {{ .Values.configName }}: |
    {
      "control": {
        "token": "${CONTROL_TOKEN}",
        "host": "${CONTROL_HOST}",
        "protocol": "${CONTROL_PROTOCOL}",
        "insecure_skip_verify": ${CONTROL_INSECURE_SKIP_VERIFY}
      },
      "corezoid": {
        "host": "https://{{ .Values.global.control.apiCorezoidDomain }}",
        "insecure_skip_verify": ${CONTROL_INSECURE_SKIP_VERIFY}
      },
      {{- if .Values.global.control.apiGWDomain }}
      "apigw": {
        "host": "https://{{ .Values.global.control.apiGWDomain }}",
        "insecure_skip_verify": ${CONTROL_INSECURE_SKIP_VERIFY}
      },
      {{- end }}
      "postgres": {
        "host": "${DB_HOST}",
        "port": ${DB_PORT},
        "database": "${DB_NAME}",
        "user": "${DB_USER}",
        "password": "${DB_PASSWORD}",
        "sslMode": "${DB_SSLMODE}"
      },
      "redis": {
        "host": "${REDIS_HOST}",
        "port": ${REDIS_PORT},
        "database": ${REDIS_DATABASE},
        "password": "${REDIS_PASSWORD}"
      },
      "metrics": {
        "port": {{ .Values.appReadinessHttpPort | default "9100" }}
      },
      {{- if $global_data.control.connectors }}
      "connectors": {
        "convId": ${CONFIG_CONNECTORS_CONVID},
        "apiLogin": ${CONFIG_CONNECTORS_APILOGIN},
        "apiSecret": "${CONFIG_CONNECTORS_APISECRET}",
        "url": "${CONFIG_CONNECTORS_COREZOID_SYNCAPI_URL}",
        "insecure_skip_verify": ${CONTROL_INSECURE_SKIP_VERIFY}
      },
      {{- end }}
      "sa": {
        "url": "${CONFIG_SA_URL}",
        "secretKey": "${CONFIG_SA_SECRETKEY}",
        "insecure_skip_verify": ${CONTROL_INSECURE_SKIP_VERIFY}
      }
    }
