apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  labels:
{{- include "control-tasks.labels" . | nindent 4 }}
data:
  config.yml: |
    {
      "control": {
        "token": {{- include "control.token" . | quote }},
        "host": "{{- include "control.Domain" . }}",
        "protocol": "{{ .Values.global.control.protocol | default "https" }}",
        "insecure_skip_verify": {{ .Values.global.control.insecure_skip_verify | default false }}
      },
      "corezoid": {
        "host": "https://{{ .Values.global.control.apiCorezoidDomain }}",
        "insecure_skip_verify": {{ .Values.global.control.insecure_skip_verify | default false }}
      },
      {{- if .Values.global.control.apiGWDomain }}
      "apigw": {
        "host": "https://{{ .Values.global.control.apiGWDomain }}",
        "insecure_skip_verify": {{ .Values.global.control.insecure_skip_verify | default false }}
      },
      {{- end }}
      "postgres": {
      {{- if .Values.global.db.bouncer }}
        "host": "pgbouncer-service",
      {{- else }}
        "host": "{{ .Values.global.db.secret.data.dbhost }}",
      {{- end }}
      {{- if .Values.global.db.bouncer }}
        "port": {{ .Values.global.db.bouncer_port }},
      {{- else }}
        "port": {{ .Values.global.db.secret.data.dbport }},
      {{- end }}
        "database": "{{ .Values.global.db.secret.data.dbname | default "control" }}",
        "user": "{{ .Values.global.db.secret.data.dbuser }}",
        "password": "{{ .Values.global.db.secret.data.dbpwd }}",
        "sslMode": "{{ .Values.global.db.secret.data.sslmode | default "disable" }}"
      },
      "redis": {
        "host": "{{ .Values.global.redis.secret.data.host }}",
        "port": {{ .Values.global.redis.secret.data.port | default "6379" }},
        "database": {{ .Values.global.control.redisDb | default 0 }},
        "password": "{{ .Values.global.redis.secret.data.password | default "" }}"
      }{{- if not .Values.global.control.cron.app_enabled }},
      "metrics": {
        "port": {{ .Values.appReadinessHttpPort | default "9100" }}
      },
    {{- if .Values.global.control.connectors }}
      "connectors": {
        "convId": {{ .Values.global.control.connectors.convId }},
        "apiLogin": {{ .Values.global.control.connectors.apiLogin }},
        "apiSecret": {{ .Values.global.control.connectors.apiSecret | quote }},
        "url": {{ .Values.global.control.corezoidSyncApiUrl | quote }},
        "insecure_skip_verify": {{ .Values.global.control.insecure_skip_verify | default false }}
      },
    {{- end }}
      "sa": {
        "url": "https://{{ .Values.global.control.auth.domain }}",
        "secretKey": {{ .Values.global.control.auth.key | quote }},
        "insecure_skip_verify": {{ .Values.global.control.insecure_skip_verify | default false }}
      }
    {{- end }}
    }
