{{- if .Values.global.serviceMonitor -}}
{{- if .Values.global.serviceMonitor.enabled -}}
apiVersion: {{ include "common.ServiceMonitor.apiVersion" . }}
kind: PodMonitor
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include "control-tasks.labels" . | nindent 4 }}
    {{- include "common.ServiceMonitor.metadata.labes" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "control-tasks.labels" . | nindent 6 }}
  podMetricsEndpoints:
  - path: {{ .Values.prometheusPath | default "/metrics" }}
    targetPort: {{ .Values.appReadinessHttpPort | default "9100" }}
    interval: {{ .Values.prometheusInterval | default "15s" }}
{{- end -}}
{{- end -}}
