apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "control.configSecretName" . }}-{{ .Values.appName }}-reader-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [
      {{ include "control.configSecretName" . | quote }},
      {{ include "control.postgresSecretName" . | quote }},
      {{ include "control.redisSecretName" . | quote }}
    ]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: [{{ include "control.tasks.configmap.name" . | quote }}]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "control.configSecretName" . }}-{{ .Values.appName }}-reader-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.appName }}-serviceaccount
roleRef:
  kind: Role
  name: {{ include "control.configSecretName" . }}-{{ .Values.appName }}-reader-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}-serviceaccount
  annotations: