{{- if .Values.global.control.control_tasks.serviceAccount -}}
{{- if .Values.global.control.control_tasks.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}-serviceaccount
  labels:
    {{- include "control-tasks.labels" . | nindent 4 }}
  {{- with .Values.global.control.control_tasks.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
