---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.imagePullSecrets.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXItaHViLm1pZGRsZXdhcmUuYml6Ijp7InVzZXJuYW1lIjoicnVubmVyIiwicGFzc3dvcmQiOiJMeXRnaGpndG5oamRjciIsImVtYWlsIjoicnVubmVyQGNvcmV6b2lkLmNvbSIsImF1dGgiOiJjblZ1Ym1WeU9reDVkR2RvYW1kMGJtaHFaR055In19fQ==
