apiVersion: v1
kind: Secret
metadata:
  name: {{ include "control.configSecretName" . }}
  labels:
    app: {{ .Values.global.control.product }}
    tier: "control"
  annotations:
    {{- include "control.configSecretAnnotations" . | nindent 4 }}
type: Opaque
data:
  configSaSecretKey: {{ .Values.global.control.auth.key | toString | b64enc }}
  {{- if .Values.global.control.connectors }}
  configConnectorsConvId: {{ .Values.global.control.connectors.convId | toString | b64enc }}
  configConnectorsApiLogin: {{ .Values.global.control.connectors.apiLogin | toString | b64enc }}
  configConnectorsApiSecret: {{ .Values.global.control.connectors.apiSecret | toString | b64enc }}
  {{- end }}
