{{- if .Values.global.db.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "control.postgresSecretName" . | quote }}
  labels:
    app: {{ .Values.global.control.product }}
    tier: "postgres"
  annotations:
    {{- include "control.postgresSecretAnnotations" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.global.db.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end}}
