apiVersion: v1
kind: Pod
metadata:
  name: postgres-post-install
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-weight: "-5"
  labels:
    tier: postgres
spec:
  containers:
    - image: {{ .Values.global.db.image }}
      imagePullPolicy: {{ .Values.global.db.imagePullPolicy | default "IfNotPresent" }}
      name: postgres-init-db
      command:
        - sh
        - -c
        - |
          until PGPASSWORD=${POSTGRES_DBSUPERUSERPWD} psql -h ${POSTGRES_DBHOST} -p $POSTGRES_PORT -d postgres -U ${POSTGRES_DBSUPERUSER} -Atc "SELECT 1"; do echo Waiting while postgres created projects table ...; sleep 3; done
          echo  "$POSTGRES_DBHOST:$POSTGRES_PORT:*:$POSTGRES_DBSUPERUSER:$POSTGRES_DBSUPERUSERPWD" > ~/.pgpass; chmod 0600 ~/.pgpass;
          echo "SELECT 'CREATE DATABASE $POSTGRES_DBNAME' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$POSTGRES_DBNAME')\gexec" | psql -h $POSTGRES_DBHOST -p $POSTGRES_PORT -d postgres -U $POSTGRES_DBSUPERUSER ;
          psql -h $POSTGRES_DBHOST -p $POSTGRES_PORT -d postgres -U $POSTGRES_DBSUPERUSER -Atc "SELECT count(*) FROM pg_catalog.pg_roles WHERE  rolname = '$POSTGRES_APPUSER';" | grep -q 1 || psql -h $POSTGRES_DBHOST -p $POSTGRES_PORT -d postgres -U $POSTGRES_DBSUPERUSER -Atc "CREATE ROLE $POSTGRES_APPUSER LOGIN PASSWORD '$POSTGRES_APPUSERPWD'; ALTER DATABASE $POSTGRES_DBNAME OWNER TO $POSTGRES_APPUSER; ALTER USER $POSTGRES_APPUSER WITH CREATEDB CREATEROLE;"
      securityContext:
        runAsUser: 70
      env:
        - name: POSTGRES_DBHOST
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.db.secret.name }}
              key: dbhost
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.db.secret.name }}
              key: dbport
        - name: POSTGRES_DBNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.db.secret.name }}
              key: dbname
        - name: POSTGRES_DBSUPERUSER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.db.secret.name }}-root
              key: dbsuperuser
        - name: POSTGRES_DBSUPERUSERPWD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.db.secret.name }}-root
              key: dbsuperuserpwd
        - name: POSTGRES_APPUSER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.db.secret.name }}
              key: dbuser
        - name: POSTGRES_APPUSERPWD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.db.secret.name }}
              key: dbpwd
  restartPolicy: Never
