{{- if .Values.global.db.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "control.postgresSecretNameRoot" . | quote }}
  labels:
    app: {{ .Values.global.control.product }}
    tier: "postgres"
  annotations:
    {{- include "control.postgresSecretAnnotations" . | nindent 4 }}
type: Opaque
data:
  dbsuperuser: {{ .Values.global.db.secret.dbsuperuser | b64enc | quote }}
  dbsuperuserpwd: {{ .Values.global.db.secret.dbsuperuserpwd | b64enc | quote }}
{{- end}}
