{{- if .Values.global.redis.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "control.redisSecretName" . | quote }}
  labels:
    app: {{ .Values.global.control.product }}
    tier: "redis"
  annotations:
    {{- include "control.redisSecretAnnotations" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.global.redis.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end}}
