{{- $control_secret_storage := "" }}
{{- if .Values.global.control.redis }}
{{- $control_secret_storage = .Values.global.control.redis.secret.data }}
{{- else }}
{{- $control_secret_storage = .Values.global.redis.secret.data }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "control.redisSecretName" . | quote }}
  labels:
    app: {{ .Values.global.control.product }}
    tier: "redis"
  annotations:
    {{- include "control.redisSecretAnnotations" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $control_secret_storage }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
